spring.application.name=sfqry
spring.profiles.active=mock
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

app.login.email=test@example.com
app.login.password=test
